name: dart3alpha
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-151.0.dev'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
